#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXeBuyt.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLXeBus")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_Hoadon(CT_Hoadon instance);
    partial void UpdateCT_Hoadon(CT_Hoadon instance);
    partial void DeleteCT_Hoadon(CT_Hoadon instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertHoadon(Hoadon instance);
    partial void UpdateHoadon(Hoadon instance);
    partial void DeleteHoadon(Hoadon instance);
    partial void InsertKhachhang(Khachhang instance);
    partial void UpdateKhachhang(Khachhang instance);
    partial void DeleteKhachhang(Khachhang instance);
    partial void InsertLoaitaikhoan(Loaitaikhoan instance);
    partial void UpdateLoaitaikhoan(Loaitaikhoan instance);
    partial void DeleteLoaitaikhoan(Loaitaikhoan instance);
    partial void InsertNhanvien(Nhanvien instance);
    partial void UpdateNhanvien(Nhanvien instance);
    partial void DeleteNhanvien(Nhanvien instance);
    partial void InsertPhanhoi(Phanhoi instance);
    partial void UpdatePhanhoi(Phanhoi instance);
    partial void DeletePhanhoi(Phanhoi instance);
    partial void InsertTaikhoan(Taikhoan instance);
    partial void UpdateTaikhoan(Taikhoan instance);
    partial void DeleteTaikhoan(Taikhoan instance);
    partial void InsertThoigianlamviec(Thoigianlamviec instance);
    partial void UpdateThoigianlamviec(Thoigianlamviec instance);
    partial void DeleteThoigianlamviec(Thoigianlamviec instance);
    partial void InsertTramxe(Tramxe instance);
    partial void UpdateTramxe(Tramxe instance);
    partial void DeleteTramxe(Tramxe instance);
    partial void InsertTuyenxe(Tuyenxe instance);
    partial void UpdateTuyenxe(Tuyenxe instance);
    partial void DeleteTuyenxe(Tuyenxe instance);
    partial void InsertVeXe(VeXe instance);
    partial void UpdateVeXe(VeXe instance);
    partial void DeleteVeXe(VeXe instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLXeBusConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_Hoadon> CT_Hoadons
		{
			get
			{
				return this.GetTable<CT_Hoadon>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<CT_Ngaylamviec> CT_Ngaylamviecs
		{
			get
			{
				return this.GetTable<CT_Ngaylamviec>();
			}
		}
		
		public System.Data.Linq.Table<CT_Tuyenxe> CT_Tuyenxes
		{
			get
			{
				return this.GetTable<CT_Tuyenxe>();
			}
		}
		
		public System.Data.Linq.Table<CT_Xe> CT_Xes
		{
			get
			{
				return this.GetTable<CT_Xe>();
			}
		}
		
		public System.Data.Linq.Table<Hoadon> Hoadons
		{
			get
			{
				return this.GetTable<Hoadon>();
			}
		}
		
		public System.Data.Linq.Table<Khachhang> Khachhangs
		{
			get
			{
				return this.GetTable<Khachhang>();
			}
		}
		
		public System.Data.Linq.Table<Loaitaikhoan> Loaitaikhoans
		{
			get
			{
				return this.GetTable<Loaitaikhoan>();
			}
		}
		
		public System.Data.Linq.Table<Nhanvien> Nhanviens
		{
			get
			{
				return this.GetTable<Nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<Phanhoi> Phanhois
		{
			get
			{
				return this.GetTable<Phanhoi>();
			}
		}
		
		public System.Data.Linq.Table<Taikhoan> Taikhoans
		{
			get
			{
				return this.GetTable<Taikhoan>();
			}
		}
		
		public System.Data.Linq.Table<Thoigianlamviec> Thoigianlamviecs
		{
			get
			{
				return this.GetTable<Thoigianlamviec>();
			}
		}
		
		public System.Data.Linq.Table<Tramxe> Tramxes
		{
			get
			{
				return this.GetTable<Tramxe>();
			}
		}
		
		public System.Data.Linq.Table<Tuyenxe> Tuyenxes
		{
			get
			{
				return this.GetTable<Tuyenxe>();
			}
		}
		
		public System.Data.Linq.Table<VeXe> VeXes
		{
			get
			{
				return this.GetTable<VeXe>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DanhSachVe")]
		public ISingleResult<sp_DanhSachVeResult> sp_DanhSachVe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> makhachhang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makhachhang);
			return ((ISingleResult<sp_DanhSachVeResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_Hoadon")]
	public partial class CT_Hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mave;
		
		private int _MaHD;
		
		private System.Nullable<int> _Trangthai;
		
		private System.Nullable<int> _Soluotsudung;
		
		private string _QRcode;
		
		private int _Id_CTHoadon;
		
		private EntityRef<VeXe> _VeXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaveChanging(int value);
    partial void OnMaveChanged();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnTrangthaiChanging(System.Nullable<int> value);
    partial void OnTrangthaiChanged();
    partial void OnSoluotsudungChanging(System.Nullable<int> value);
    partial void OnSoluotsudungChanged();
    partial void OnQRcodeChanging(string value);
    partial void OnQRcodeChanged();
    partial void OnId_CTHoadonChanging(int value);
    partial void OnId_CTHoadonChanged();
    #endregion
		
		public CT_Hoadon()
		{
			this._VeXe = default(EntityRef<VeXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mave", DbType="Int NOT NULL")]
		public int Mave
		{
			get
			{
				return this._Mave;
			}
			set
			{
				if ((this._Mave != value))
				{
					if (this._VeXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaveChanging(value);
					this.SendPropertyChanging();
					this._Mave = value;
					this.SendPropertyChanged("Mave");
					this.OnMaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL")]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Int")]
		public System.Nullable<int> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluotsudung", DbType="Int")]
		public System.Nullable<int> Soluotsudung
		{
			get
			{
				return this._Soluotsudung;
			}
			set
			{
				if ((this._Soluotsudung != value))
				{
					this.OnSoluotsudungChanging(value);
					this.SendPropertyChanging();
					this._Soluotsudung = value;
					this.SendPropertyChanged("Soluotsudung");
					this.OnSoluotsudungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QRcode", DbType="NVarChar(MAX)")]
		public string QRcode
		{
			get
			{
				return this._QRcode;
			}
			set
			{
				if ((this._QRcode != value))
				{
					this.OnQRcodeChanging(value);
					this.SendPropertyChanging();
					this._QRcode = value;
					this.SendPropertyChanged("QRcode");
					this.OnQRcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_CTHoadon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_CTHoadon
		{
			get
			{
				return this._Id_CTHoadon;
			}
			set
			{
				if ((this._Id_CTHoadon != value))
				{
					this.OnId_CTHoadonChanging(value);
					this.SendPropertyChanging();
					this._Id_CTHoadon = value;
					this.SendPropertyChanged("Id_CTHoadon");
					this.OnId_CTHoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VeXe_CT_Hoadon", Storage="_VeXe", ThisKey="Mave", OtherKey="Mave", IsForeignKey=true)]
		public VeXe VeXe
		{
			get
			{
				return this._VeXe.Entity;
			}
			set
			{
				VeXe previousValue = this._VeXe.Entity;
				if (((previousValue != value) 
							|| (this._VeXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VeXe.Entity = null;
						previousValue.CT_Hoadons.Remove(this);
					}
					this._VeXe.Entity = value;
					if ((value != null))
					{
						value.CT_Hoadons.Add(this);
						this._Mave = value.Mave;
					}
					else
					{
						this._Mave = default(int);
					}
					this.SendPropertyChanged("VeXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaXe;
		
		private System.Nullable<System.TimeSpan> _Thoigianhoatdong;
		
		private System.Nullable<System.TimeSpan> _Thoigianchay;
		
		private string _Bienso;
		
		private string _Trangthai;
		
		private int _Matuyen;
		
		private System.Nullable<int> _Sochongoi;
		
		private EntityRef<Tuyenxe> _Tuyenxe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(int value);
    partial void OnMaXeChanged();
    partial void OnThoigianhoatdongChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianhoatdongChanged();
    partial void OnThoigianchayChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianchayChanged();
    partial void OnBiensoChanging(string value);
    partial void OnBiensoChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    partial void OnMatuyenChanging(int value);
    partial void OnMatuyenChanged();
    partial void OnSochongoiChanging(System.Nullable<int> value);
    partial void OnSochongoiChanged();
    #endregion
		
		public Xe()
		{
			this._Tuyenxe = default(EntityRef<Tuyenxe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianhoatdong", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianhoatdong
		{
			get
			{
				return this._Thoigianhoatdong;
			}
			set
			{
				if ((this._Thoigianhoatdong != value))
				{
					this.OnThoigianhoatdongChanging(value);
					this.SendPropertyChanging();
					this._Thoigianhoatdong = value;
					this.SendPropertyChanged("Thoigianhoatdong");
					this.OnThoigianhoatdongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianchay", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianchay
		{
			get
			{
				return this._Thoigianchay;
			}
			set
			{
				if ((this._Thoigianchay != value))
				{
					this.OnThoigianchayChanging(value);
					this.SendPropertyChanging();
					this._Thoigianchay = value;
					this.SendPropertyChanged("Thoigianchay");
					this.OnThoigianchayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bienso", DbType="Char(10)")]
		public string Bienso
		{
			get
			{
				return this._Bienso;
			}
			set
			{
				if ((this._Bienso != value))
				{
					this.OnBiensoChanging(value);
					this.SendPropertyChanging();
					this._Bienso = value;
					this.SendPropertyChanged("Bienso");
					this.OnBiensoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matuyen", DbType="Int NOT NULL")]
		public int Matuyen
		{
			get
			{
				return this._Matuyen;
			}
			set
			{
				if ((this._Matuyen != value))
				{
					if (this._Tuyenxe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatuyenChanging(value);
					this.SendPropertyChanging();
					this._Matuyen = value;
					this.SendPropertyChanged("Matuyen");
					this.OnMatuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochongoi", DbType="Int")]
		public System.Nullable<int> Sochongoi
		{
			get
			{
				return this._Sochongoi;
			}
			set
			{
				if ((this._Sochongoi != value))
				{
					this.OnSochongoiChanging(value);
					this.SendPropertyChanging();
					this._Sochongoi = value;
					this.SendPropertyChanged("Sochongoi");
					this.OnSochongoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tuyenxe_Xe", Storage="_Tuyenxe", ThisKey="Matuyen", OtherKey="Matuyen", IsForeignKey=true)]
		public Tuyenxe Tuyenxe
		{
			get
			{
				return this._Tuyenxe.Entity;
			}
			set
			{
				Tuyenxe previousValue = this._Tuyenxe.Entity;
				if (((previousValue != value) 
							|| (this._Tuyenxe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tuyenxe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._Tuyenxe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._Matuyen = value.Matuyen;
					}
					else
					{
						this._Matuyen = default(int);
					}
					this.SendPropertyChanged("Tuyenxe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_Ngaylamviec")]
	public partial class CT_Ngaylamviec
	{
		
		private int _Manhanvien;
		
		private int _Maxe;
		
		private int _Id_Thoigianlamviec;
		
		private System.Nullable<System.DateTime> _Ngaylamviec;
		
		public CT_Ngaylamviec()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", DbType="Int NOT NULL")]
		public int Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this._Manhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maxe", DbType="Int NOT NULL")]
		public int Maxe
		{
			get
			{
				return this._Maxe;
			}
			set
			{
				if ((this._Maxe != value))
				{
					this._Maxe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Thoigianlamviec", DbType="Int NOT NULL")]
		public int Id_Thoigianlamviec
		{
			get
			{
				return this._Id_Thoigianlamviec;
			}
			set
			{
				if ((this._Id_Thoigianlamviec != value))
				{
					this._Id_Thoigianlamviec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylamviec", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaylamviec
		{
			get
			{
				return this._Ngaylamviec;
			}
			set
			{
				if ((this._Ngaylamviec != value))
				{
					this._Ngaylamviec = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_Tuyenxe")]
	public partial class CT_Tuyenxe
	{
		
		private int _Matuyen;
		
		private int _Matram;
		
		public CT_Tuyenxe()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matuyen", DbType="Int NOT NULL")]
		public int Matuyen
		{
			get
			{
				return this._Matuyen;
			}
			set
			{
				if ((this._Matuyen != value))
				{
					this._Matuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matram", DbType="Int NOT NULL")]
		public int Matram
		{
			get
			{
				return this._Matram;
			}
			set
			{
				if ((this._Matram != value))
				{
					this._Matram = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_Xe")]
	public partial class CT_Xe
	{
		
		private int _Manhanvien;
		
		private int _Maxe;
		
		public CT_Xe()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", DbType="Int NOT NULL")]
		public int Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this._Manhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maxe", DbType="Int NOT NULL")]
		public int Maxe
		{
			get
			{
				return this._Maxe;
			}
			set
			{
				if ((this._Maxe != value))
				{
					this._Maxe = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoadon")]
	public partial class Hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _Ngaymua;
		
		private int _Makhachhang;
		
		private System.Nullable<int> _Trangthai;
		
		private int _MaHD;
		
		private EntityRef<Khachhang> _Khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgaymuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaymuaChanged();
    partial void OnMakhachhangChanging(int value);
    partial void OnMakhachhangChanged();
    partial void OnTrangthaiChanging(System.Nullable<int> value);
    partial void OnTrangthaiChanged();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    #endregion
		
		public Hoadon()
		{
			this._Khachhang = default(EntityRef<Khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaymua", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaymua
		{
			get
			{
				return this._Ngaymua;
			}
			set
			{
				if ((this._Ngaymua != value))
				{
					this.OnNgaymuaChanging(value);
					this.SendPropertyChanging();
					this._Ngaymua = value;
					this.SendPropertyChanged("Ngaymua");
					this.OnNgaymuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", DbType="Int NOT NULL")]
		public int Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					if (this._Khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhachhangChanging(value);
					this.SendPropertyChanging();
					this._Makhachhang = value;
					this.SendPropertyChanged("Makhachhang");
					this.OnMakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Int")]
		public System.Nullable<int> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Hoadon", Storage="_Khachhang", ThisKey="Makhachhang", OtherKey="Makhachhang", IsForeignKey=true)]
		public Khachhang Khachhang
		{
			get
			{
				return this._Khachhang.Entity;
			}
			set
			{
				Khachhang previousValue = this._Khachhang.Entity;
				if (((previousValue != value) 
							|| (this._Khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khachhang.Entity = null;
						previousValue.Hoadons.Remove(this);
					}
					this._Khachhang.Entity = value;
					if ((value != null))
					{
						value.Hoadons.Add(this);
						this._Makhachhang = value.Makhachhang;
					}
					else
					{
						this._Makhachhang = default(int);
					}
					this.SendPropertyChanged("Khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khachhang")]
	public partial class Khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Makhachhang;
		
		private string _Ten;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _CCCD;
		
		private string _TheHSSV;
		
		private System.Nullable<bool> _Gioitinh;
		
		private string _Diachi;
		
		private int _Id_Taikhoan;
		
		private EntitySet<Hoadon> _Hoadons;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhachhangChanging(int value);
    partial void OnMakhachhangChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnTheHSSVChanging(string value);
    partial void OnTheHSSVChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnId_TaikhoanChanging(int value);
    partial void OnId_TaikhoanChanged();
    #endregion
		
		public Khachhang()
		{
			this._Hoadons = new EntitySet<Hoadon>(new Action<Hoadon>(this.attach_Hoadons), new Action<Hoadon>(this.detach_Hoadons));
			this._Taikhoan = default(EntityRef<Taikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					this.OnMakhachhangChanging(value);
					this.SendPropertyChanging();
					this._Makhachhang = value;
					this.SendPropertyChanged("Makhachhang");
					this.OnMakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Char(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheHSSV", DbType="Char(10)")]
		public string TheHSSV
		{
			get
			{
				return this._TheHSSV;
			}
			set
			{
				if ((this._TheHSSV != value))
				{
					this.OnTheHSSVChanging(value);
					this.SendPropertyChanging();
					this._TheHSSV = value;
					this.SendPropertyChanged("TheHSSV");
					this.OnTheHSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Taikhoan", DbType="Int NOT NULL")]
		public int Id_Taikhoan
		{
			get
			{
				return this._Id_Taikhoan;
			}
			set
			{
				if ((this._Id_Taikhoan != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Id_Taikhoan = value;
					this.SendPropertyChanged("Id_Taikhoan");
					this.OnId_TaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Hoadon", Storage="_Hoadons", ThisKey="Makhachhang", OtherKey="Makhachhang")]
		public EntitySet<Hoadon> Hoadons
		{
			get
			{
				return this._Hoadons;
			}
			set
			{
				this._Hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Khachhang", Storage="_Taikhoan", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.Khachhangs.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.Khachhangs.Add(this);
						this._Id_Taikhoan = value.Id_Taikhoan;
					}
					else
					{
						this._Id_Taikhoan = default(int);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = this;
		}
		
		private void detach_Hoadons(Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loaitaikhoan")]
	public partial class Loaitaikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Loaitaikhoan;
		
		private string _Ten;
		
		private string _Maloai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_LoaitaikhoanChanging(int value);
    partial void OnId_LoaitaikhoanChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    #endregion
		
		public Loaitaikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Loaitaikhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Loaitaikhoan
		{
			get
			{
				return this._Id_Loaitaikhoan;
			}
			set
			{
				if ((this._Id_Loaitaikhoan != value))
				{
					this.OnId_LoaitaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Id_Loaitaikhoan = value;
					this.SendPropertyChanged("Id_Loaitaikhoan");
					this.OnId_LoaitaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NVarChar(50)")]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhanvien")]
	public partial class Nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Manhanvien;
		
		private string _Ten;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Diachi;
		
		private System.Nullable<bool> _Gioitinh;
		
		private System.Nullable<System.DateTime> _Ngayvaolam;
		
		private string _Chucvu;
		
		private System.Nullable<decimal> _Luong;
		
		private string _CCCD;
		
		private int _Id_Taikhoan;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhanvienChanging(int value);
    partial void OnManhanvienChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnNgayvaolamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayvaolamChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OnLuongChanging(System.Nullable<decimal> value);
    partial void OnLuongChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnId_TaikhoanChanging(int value);
    partial void OnId_TaikhoanChanged();
    #endregion
		
		public Nhanvien()
		{
			this._Taikhoan = default(EntityRef<Taikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this.OnManhanvienChanging(value);
					this.SendPropertyChanging();
					this._Manhanvien = value;
					this.SendPropertyChanged("Manhanvien");
					this.OnManhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayvaolam", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayvaolam
		{
			get
			{
				return this._Ngayvaolam;
			}
			set
			{
				if ((this._Ngayvaolam != value))
				{
					this.OnNgayvaolamChanging(value);
					this.SendPropertyChanging();
					this._Ngayvaolam = value;
					this.SendPropertyChanged("Ngayvaolam");
					this.OnNgayvaolamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(50)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Char(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Taikhoan", DbType="Int NOT NULL")]
		public int Id_Taikhoan
		{
			get
			{
				return this._Id_Taikhoan;
			}
			set
			{
				if ((this._Id_Taikhoan != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Id_Taikhoan = value;
					this.SendPropertyChanged("Id_Taikhoan");
					this.OnId_TaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Nhanvien", Storage="_Taikhoan", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.Nhanviens.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.Nhanviens.Add(this);
						this._Id_Taikhoan = value.Id_Taikhoan;
					}
					else
					{
						this._Id_Taikhoan = default(int);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phanhoi")]
	public partial class Phanhoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphanhoi;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngayphanhoi;
		
		private int _Id_Taikhoan;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphanhoiChanging(int value);
    partial void OnMaphanhoiChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnNgayphanhoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayphanhoiChanged();
    partial void OnId_TaikhoanChanging(int value);
    partial void OnId_TaikhoanChanged();
    #endregion
		
		public Phanhoi()
		{
			this._Taikhoan = default(EntityRef<Taikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphanhoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Maphanhoi
		{
			get
			{
				return this._Maphanhoi;
			}
			set
			{
				if ((this._Maphanhoi != value))
				{
					this.OnMaphanhoiChanging(value);
					this.SendPropertyChanging();
					this._Maphanhoi = value;
					this.SendPropertyChanged("Maphanhoi");
					this.OnMaphanhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(150)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayphanhoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayphanhoi
		{
			get
			{
				return this._Ngayphanhoi;
			}
			set
			{
				if ((this._Ngayphanhoi != value))
				{
					this.OnNgayphanhoiChanging(value);
					this.SendPropertyChanging();
					this._Ngayphanhoi = value;
					this.SendPropertyChanged("Ngayphanhoi");
					this.OnNgayphanhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Taikhoan", DbType="Int NOT NULL")]
		public int Id_Taikhoan
		{
			get
			{
				return this._Id_Taikhoan;
			}
			set
			{
				if ((this._Id_Taikhoan != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Id_Taikhoan = value;
					this.SendPropertyChanged("Id_Taikhoan");
					this.OnId_TaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Phanhoi", Storage="_Taikhoan", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.Phanhois.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.Phanhois.Add(this);
						this._Id_Taikhoan = value.Id_Taikhoan;
					}
					else
					{
						this._Id_Taikhoan = default(int);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taikhoan")]
	public partial class Taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Taikhoan;
		
		private string _Tentaikhoan;
		
		private string _Matkhau;
		
		private string _Email;
		
		private string _Sodienthoai;
		
		private System.Nullable<int> _Code;
		
		private string _Tinhtrang;
		
		private System.Nullable<decimal> _Sodu;
		
		private string _Maloai;
		
		private EntitySet<Khachhang> _Khachhangs;
		
		private EntitySet<Nhanvien> _Nhanviens;
		
		private EntitySet<Phanhoi> _Phanhois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TaikhoanChanging(int value);
    partial void OnId_TaikhoanChanged();
    partial void OnTentaikhoanChanging(string value);
    partial void OnTentaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSodienthoaiChanging(string value);
    partial void OnSodienthoaiChanged();
    partial void OnCodeChanging(System.Nullable<int> value);
    partial void OnCodeChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnSoduChanging(System.Nullable<decimal> value);
    partial void OnSoduChanged();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    #endregion
		
		public Taikhoan()
		{
			this._Khachhangs = new EntitySet<Khachhang>(new Action<Khachhang>(this.attach_Khachhangs), new Action<Khachhang>(this.detach_Khachhangs));
			this._Nhanviens = new EntitySet<Nhanvien>(new Action<Nhanvien>(this.attach_Nhanviens), new Action<Nhanvien>(this.detach_Nhanviens));
			this._Phanhois = new EntitySet<Phanhoi>(new Action<Phanhoi>(this.attach_Phanhois), new Action<Phanhoi>(this.detach_Phanhois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Taikhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Taikhoan
		{
			get
			{
				return this._Id_Taikhoan;
			}
			set
			{
				if ((this._Id_Taikhoan != value))
				{
					this.OnId_TaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Id_Taikhoan = value;
					this.SendPropertyChanged("Id_Taikhoan");
					this.OnId_TaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentaikhoan", DbType="NVarChar(50)")]
		public string Tentaikhoan
		{
			get
			{
				return this._Tentaikhoan;
			}
			set
			{
				if ((this._Tentaikhoan != value))
				{
					this.OnTentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Tentaikhoan = value;
					this.SendPropertyChanged("Tentaikhoan");
					this.OnTentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="Char(10)")]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int")]
		public System.Nullable<int> Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(100)")]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Sodu
		{
			get
			{
				return this._Sodu;
			}
			set
			{
				if ((this._Sodu != value))
				{
					this.OnSoduChanging(value);
					this.SendPropertyChanging();
					this._Sodu = value;
					this.SendPropertyChanged("Sodu");
					this.OnSoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NChar(10)")]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Khachhang", Storage="_Khachhangs", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan")]
		public EntitySet<Khachhang> Khachhangs
		{
			get
			{
				return this._Khachhangs;
			}
			set
			{
				this._Khachhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Nhanvien", Storage="_Nhanviens", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan")]
		public EntitySet<Nhanvien> Nhanviens
		{
			get
			{
				return this._Nhanviens;
			}
			set
			{
				this._Nhanviens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Phanhoi", Storage="_Phanhois", ThisKey="Id_Taikhoan", OtherKey="Id_Taikhoan")]
		public EntitySet<Phanhoi> Phanhois
		{
			get
			{
				return this._Phanhois;
			}
			set
			{
				this._Phanhois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Khachhangs(Khachhang entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_Khachhangs(Khachhang entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_Nhanviens(Nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_Nhanviens(Nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_Phanhois(Phanhoi entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_Phanhois(Phanhoi entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thoigianlamviec")]
	public partial class Thoigianlamviec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Thoigianlamviec;
		
		private System.Nullable<System.TimeSpan> _Thoigianbatdau;
		
		private System.Nullable<System.TimeSpan> _Thoigianketthuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ThoigianlamviecChanging(int value);
    partial void OnId_ThoigianlamviecChanged();
    partial void OnThoigianbatdauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianbatdauChanged();
    partial void OnThoigianketthucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianketthucChanged();
    #endregion
		
		public Thoigianlamviec()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Thoigianlamviec", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Thoigianlamviec
		{
			get
			{
				return this._Id_Thoigianlamviec;
			}
			set
			{
				if ((this._Id_Thoigianlamviec != value))
				{
					this.OnId_ThoigianlamviecChanging(value);
					this.SendPropertyChanging();
					this._Id_Thoigianlamviec = value;
					this.SendPropertyChanged("Id_Thoigianlamviec");
					this.OnId_ThoigianlamviecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianbatdau", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianbatdau
		{
			get
			{
				return this._Thoigianbatdau;
			}
			set
			{
				if ((this._Thoigianbatdau != value))
				{
					this.OnThoigianbatdauChanging(value);
					this.SendPropertyChanging();
					this._Thoigianbatdau = value;
					this.SendPropertyChanged("Thoigianbatdau");
					this.OnThoigianbatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianketthuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianketthuc
		{
			get
			{
				return this._Thoigianketthuc;
			}
			set
			{
				if ((this._Thoigianketthuc != value))
				{
					this.OnThoigianketthucChanging(value);
					this.SendPropertyChanging();
					this._Thoigianketthuc = value;
					this.SendPropertyChanged("Thoigianketthuc");
					this.OnThoigianketthucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tramxe")]
	public partial class Tramxe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matram;
		
		private string _Tentram;
		
		private string _Tentuyenduong;
		
		private string _Toado;
		
		private string _Manhung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatramChanging(int value);
    partial void OnMatramChanged();
    partial void OnTentramChanging(string value);
    partial void OnTentramChanged();
    partial void OnTentuyenduongChanging(string value);
    partial void OnTentuyenduongChanged();
    partial void OnToadoChanging(string value);
    partial void OnToadoChanged();
    partial void OnManhungChanging(string value);
    partial void OnManhungChanged();
    #endregion
		
		public Tramxe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matram", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Matram
		{
			get
			{
				return this._Matram;
			}
			set
			{
				if ((this._Matram != value))
				{
					this.OnMatramChanging(value);
					this.SendPropertyChanging();
					this._Matram = value;
					this.SendPropertyChanged("Matram");
					this.OnMatramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentram", DbType="NVarChar(100)")]
		public string Tentram
		{
			get
			{
				return this._Tentram;
			}
			set
			{
				if ((this._Tentram != value))
				{
					this.OnTentramChanging(value);
					this.SendPropertyChanging();
					this._Tentram = value;
					this.SendPropertyChanged("Tentram");
					this.OnTentramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentuyenduong", DbType="NVarChar(50)")]
		public string Tentuyenduong
		{
			get
			{
				return this._Tentuyenduong;
			}
			set
			{
				if ((this._Tentuyenduong != value))
				{
					this.OnTentuyenduongChanging(value);
					this.SendPropertyChanging();
					this._Tentuyenduong = value;
					this.SendPropertyChanged("Tentuyenduong");
					this.OnTentuyenduongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Toado", DbType="NVarChar(MAX)")]
		public string Toado
		{
			get
			{
				return this._Toado;
			}
			set
			{
				if ((this._Toado != value))
				{
					this.OnToadoChanging(value);
					this.SendPropertyChanging();
					this._Toado = value;
					this.SendPropertyChanged("Toado");
					this.OnToadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhung", DbType="NVarChar(MAX)")]
		public string Manhung
		{
			get
			{
				return this._Manhung;
			}
			set
			{
				if ((this._Manhung != value))
				{
					this.OnManhungChanging(value);
					this.SendPropertyChanging();
					this._Manhung = value;
					this.SendPropertyChanged("Manhung");
					this.OnManhungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tuyenxe")]
	public partial class Tuyenxe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matuyen;
		
		private System.Nullable<int> _Tuyenso;
		
		private string _Tentuyen;
		
		private System.Nullable<System.TimeSpan> _Thoigianbatdau;
		
		private System.Nullable<System.TimeSpan> _Thoigianketthuc;
		
		private string _Luotdi;
		
		private string _Luotve;
		
		private string _Loaituyen;
		
		private string _Thoigianchay;
		
		private string _Giancachtuyen;
		
		private System.Nullable<int> _Sochuyen;
		
		private EntitySet<Xe> _Xes;
		
		private EntitySet<VeXe> _VeXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatuyenChanging(int value);
    partial void OnMatuyenChanged();
    partial void OnTuyensoChanging(System.Nullable<int> value);
    partial void OnTuyensoChanged();
    partial void OnTentuyenChanging(string value);
    partial void OnTentuyenChanged();
    partial void OnThoigianbatdauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianbatdauChanged();
    partial void OnThoigianketthucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoigianketthucChanged();
    partial void OnLuotdiChanging(string value);
    partial void OnLuotdiChanged();
    partial void OnLuotveChanging(string value);
    partial void OnLuotveChanged();
    partial void OnLoaituyenChanging(string value);
    partial void OnLoaituyenChanged();
    partial void OnThoigianchayChanging(string value);
    partial void OnThoigianchayChanged();
    partial void OnGiancachtuyenChanging(string value);
    partial void OnGiancachtuyenChanged();
    partial void OnSochuyenChanging(System.Nullable<int> value);
    partial void OnSochuyenChanged();
    #endregion
		
		public Tuyenxe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			this._VeXes = new EntitySet<VeXe>(new Action<VeXe>(this.attach_VeXes), new Action<VeXe>(this.detach_VeXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Matuyen
		{
			get
			{
				return this._Matuyen;
			}
			set
			{
				if ((this._Matuyen != value))
				{
					this.OnMatuyenChanging(value);
					this.SendPropertyChanging();
					this._Matuyen = value;
					this.SendPropertyChanged("Matuyen");
					this.OnMatuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuyenso", DbType="Int")]
		public System.Nullable<int> Tuyenso
		{
			get
			{
				return this._Tuyenso;
			}
			set
			{
				if ((this._Tuyenso != value))
				{
					this.OnTuyensoChanging(value);
					this.SendPropertyChanging();
					this._Tuyenso = value;
					this.SendPropertyChanged("Tuyenso");
					this.OnTuyensoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentuyen", DbType="NVarChar(100)")]
		public string Tentuyen
		{
			get
			{
				return this._Tentuyen;
			}
			set
			{
				if ((this._Tentuyen != value))
				{
					this.OnTentuyenChanging(value);
					this.SendPropertyChanging();
					this._Tentuyen = value;
					this.SendPropertyChanged("Tentuyen");
					this.OnTentuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianbatdau", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianbatdau
		{
			get
			{
				return this._Thoigianbatdau;
			}
			set
			{
				if ((this._Thoigianbatdau != value))
				{
					this.OnThoigianbatdauChanging(value);
					this.SendPropertyChanging();
					this._Thoigianbatdau = value;
					this.SendPropertyChanged("Thoigianbatdau");
					this.OnThoigianbatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianketthuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoigianketthuc
		{
			get
			{
				return this._Thoigianketthuc;
			}
			set
			{
				if ((this._Thoigianketthuc != value))
				{
					this.OnThoigianketthucChanging(value);
					this.SendPropertyChanging();
					this._Thoigianketthuc = value;
					this.SendPropertyChanged("Thoigianketthuc");
					this.OnThoigianketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luotdi", DbType="NVarChar(200)")]
		public string Luotdi
		{
			get
			{
				return this._Luotdi;
			}
			set
			{
				if ((this._Luotdi != value))
				{
					this.OnLuotdiChanging(value);
					this.SendPropertyChanging();
					this._Luotdi = value;
					this.SendPropertyChanged("Luotdi");
					this.OnLuotdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luotve", DbType="NVarChar(200)")]
		public string Luotve
		{
			get
			{
				return this._Luotve;
			}
			set
			{
				if ((this._Luotve != value))
				{
					this.OnLuotveChanging(value);
					this.SendPropertyChanging();
					this._Luotve = value;
					this.SendPropertyChanged("Luotve");
					this.OnLuotveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaituyen", DbType="VarChar(50)")]
		public string Loaituyen
		{
			get
			{
				return this._Loaituyen;
			}
			set
			{
				if ((this._Loaituyen != value))
				{
					this.OnLoaituyenChanging(value);
					this.SendPropertyChanging();
					this._Loaituyen = value;
					this.SendPropertyChanged("Loaituyen");
					this.OnLoaituyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianchay", DbType="NVarChar(50)")]
		public string Thoigianchay
		{
			get
			{
				return this._Thoigianchay;
			}
			set
			{
				if ((this._Thoigianchay != value))
				{
					this.OnThoigianchayChanging(value);
					this.SendPropertyChanging();
					this._Thoigianchay = value;
					this.SendPropertyChanged("Thoigianchay");
					this.OnThoigianchayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giancachtuyen", DbType="NVarChar(50)")]
		public string Giancachtuyen
		{
			get
			{
				return this._Giancachtuyen;
			}
			set
			{
				if ((this._Giancachtuyen != value))
				{
					this.OnGiancachtuyenChanging(value);
					this.SendPropertyChanging();
					this._Giancachtuyen = value;
					this.SendPropertyChanged("Giancachtuyen");
					this.OnGiancachtuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochuyen", DbType="Int")]
		public System.Nullable<int> Sochuyen
		{
			get
			{
				return this._Sochuyen;
			}
			set
			{
				if ((this._Sochuyen != value))
				{
					this.OnSochuyenChanging(value);
					this.SendPropertyChanging();
					this._Sochuyen = value;
					this.SendPropertyChanged("Sochuyen");
					this.OnSochuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tuyenxe_Xe", Storage="_Xes", ThisKey="Matuyen", OtherKey="Matuyen")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tuyenxe_VeXe", Storage="_VeXes", ThisKey="Matuyen", OtherKey="Matuyen")]
		public EntitySet<VeXe> VeXes
		{
			get
			{
				return this._VeXes;
			}
			set
			{
				this._VeXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.Tuyenxe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.Tuyenxe = null;
		}
		
		private void attach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.Tuyenxe = this;
		}
		
		private void detach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.Tuyenxe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VeXe")]
	public partial class VeXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mave;
		
		private System.Nullable<System.DateTime> _Ngayphathanh;
		
		private System.Nullable<System.DateTime> _Ngayhethan;
		
		private string _Tinhtrang;
		
		private int _Matuyen;
		
		private System.Nullable<int> _Loaive;
		
		private System.Nullable<bool> _Vethang;
		
		private System.Nullable<decimal> _Giatien;
		
		private EntitySet<CT_Hoadon> _CT_Hoadons;
		
		private EntityRef<Tuyenxe> _Tuyenxe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaveChanging(int value);
    partial void OnMaveChanged();
    partial void OnNgayphathanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayphathanhChanged();
    partial void OnNgayhethanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayhethanChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnMatuyenChanging(int value);
    partial void OnMatuyenChanged();
    partial void OnLoaiveChanging(System.Nullable<int> value);
    partial void OnLoaiveChanged();
    partial void OnVethangChanging(System.Nullable<bool> value);
    partial void OnVethangChanged();
    partial void OnGiatienChanging(System.Nullable<decimal> value);
    partial void OnGiatienChanged();
    #endregion
		
		public VeXe()
		{
			this._CT_Hoadons = new EntitySet<CT_Hoadon>(new Action<CT_Hoadon>(this.attach_CT_Hoadons), new Action<CT_Hoadon>(this.detach_CT_Hoadons));
			this._Tuyenxe = default(EntityRef<Tuyenxe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mave", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mave
		{
			get
			{
				return this._Mave;
			}
			set
			{
				if ((this._Mave != value))
				{
					this.OnMaveChanging(value);
					this.SendPropertyChanging();
					this._Mave = value;
					this.SendPropertyChanged("Mave");
					this.OnMaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayphathanh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayphathanh
		{
			get
			{
				return this._Ngayphathanh;
			}
			set
			{
				if ((this._Ngayphathanh != value))
				{
					this.OnNgayphathanhChanging(value);
					this.SendPropertyChanging();
					this._Ngayphathanh = value;
					this.SendPropertyChanged("Ngayphathanh");
					this.OnNgayphathanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayhethan", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayhethan
		{
			get
			{
				return this._Ngayhethan;
			}
			set
			{
				if ((this._Ngayhethan != value))
				{
					this.OnNgayhethanChanging(value);
					this.SendPropertyChanging();
					this._Ngayhethan = value;
					this.SendPropertyChanged("Ngayhethan");
					this.OnNgayhethanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(50)")]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matuyen", DbType="Int NOT NULL")]
		public int Matuyen
		{
			get
			{
				return this._Matuyen;
			}
			set
			{
				if ((this._Matuyen != value))
				{
					if (this._Tuyenxe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatuyenChanging(value);
					this.SendPropertyChanging();
					this._Matuyen = value;
					this.SendPropertyChanged("Matuyen");
					this.OnMatuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaive", DbType="Int")]
		public System.Nullable<int> Loaive
		{
			get
			{
				return this._Loaive;
			}
			set
			{
				if ((this._Loaive != value))
				{
					this.OnLoaiveChanging(value);
					this.SendPropertyChanging();
					this._Loaive = value;
					this.SendPropertyChanged("Loaive");
					this.OnLoaiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vethang", DbType="Bit")]
		public System.Nullable<bool> Vethang
		{
			get
			{
				return this._Vethang;
			}
			set
			{
				if ((this._Vethang != value))
				{
					this.OnVethangChanging(value);
					this.SendPropertyChanging();
					this._Vethang = value;
					this.SendPropertyChanged("Vethang");
					this.OnVethangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giatien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giatien
		{
			get
			{
				return this._Giatien;
			}
			set
			{
				if ((this._Giatien != value))
				{
					this.OnGiatienChanging(value);
					this.SendPropertyChanging();
					this._Giatien = value;
					this.SendPropertyChanged("Giatien");
					this.OnGiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VeXe_CT_Hoadon", Storage="_CT_Hoadons", ThisKey="Mave", OtherKey="Mave")]
		public EntitySet<CT_Hoadon> CT_Hoadons
		{
			get
			{
				return this._CT_Hoadons;
			}
			set
			{
				this._CT_Hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tuyenxe_VeXe", Storage="_Tuyenxe", ThisKey="Matuyen", OtherKey="Matuyen", IsForeignKey=true)]
		public Tuyenxe Tuyenxe
		{
			get
			{
				return this._Tuyenxe.Entity;
			}
			set
			{
				Tuyenxe previousValue = this._Tuyenxe.Entity;
				if (((previousValue != value) 
							|| (this._Tuyenxe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tuyenxe.Entity = null;
						previousValue.VeXes.Remove(this);
					}
					this._Tuyenxe.Entity = value;
					if ((value != null))
					{
						value.VeXes.Add(this);
						this._Matuyen = value.Matuyen;
					}
					else
					{
						this._Matuyen = default(int);
					}
					this.SendPropertyChanged("Tuyenxe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_Hoadons(CT_Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.VeXe = this;
		}
		
		private void detach_CT_Hoadons(CT_Hoadon entity)
		{
			this.SendPropertyChanging();
			entity.VeXe = null;
		}
	}
	
	public partial class sp_DanhSachVeResult
	{
		
		private System.Nullable<System.DateTime> _Ngaymua;
		
		private int _Makhachhang;
		
		private System.Nullable<int> _Trangthai;
		
		private int _MaHD;
		
		private System.Nullable<int> _Mave;
		
		private System.Nullable<int> _Trangthai1;
		
		private System.Nullable<int> _Soluotsudung;
		
		private string _QRcode;
		
		private System.Nullable<int> _Id_CTHoadon;
		
		public sp_DanhSachVeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaymua", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaymua
		{
			get
			{
				return this._Ngaymua;
			}
			set
			{
				if ((this._Ngaymua != value))
				{
					this._Ngaymua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", DbType="Int NOT NULL")]
		public int Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					this._Makhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Int")]
		public System.Nullable<int> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this._Trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL")]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this._MaHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mave", DbType="Int")]
		public System.Nullable<int> Mave
		{
			get
			{
				return this._Mave;
			}
			set
			{
				if ((this._Mave != value))
				{
					this._Mave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai1", DbType="Int")]
		public System.Nullable<int> Trangthai1
		{
			get
			{
				return this._Trangthai1;
			}
			set
			{
				if ((this._Trangthai1 != value))
				{
					this._Trangthai1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluotsudung", DbType="Int")]
		public System.Nullable<int> Soluotsudung
		{
			get
			{
				return this._Soluotsudung;
			}
			set
			{
				if ((this._Soluotsudung != value))
				{
					this._Soluotsudung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QRcode", DbType="NVarChar(MAX)")]
		public string QRcode
		{
			get
			{
				return this._QRcode;
			}
			set
			{
				if ((this._QRcode != value))
				{
					this._QRcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_CTHoadon", DbType="Int")]
		public System.Nullable<int> Id_CTHoadon
		{
			get
			{
				return this._Id_CTHoadon;
			}
			set
			{
				if ((this._Id_CTHoadon != value))
				{
					this._Id_CTHoadon = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
